backend/backend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.staticfiles.views import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='index.html', extra_context={
        "ignore_header": True
    }, redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),  # for user signup
    path('cobra/', include('cobra_wrapper.urls')),
    path('database/', include('bigg_database.urls')),
    path('data/', include('data_wrapper.urls')),
    path('share/', include('share.urls')),
    path('favicon.ico', serve, {'path': 'icon/favicon.ico'}),
]

backend/cobra_wrapper/urls.py
from django.urls import path

from . import views, api_views

app_name = 'cobra_wrapper'
urlpatterns = [
    path('models/', views.CobraModelListView.as_view(), name='cobramodel_list'),
    path('models/<int:pk>/', views.CobraModelDetailView.as_view(), name='cobramodel_detail'),
    path('models/<int:pk>/map/', views.CobraModelMapView.as_view(), name='cobramodel_map'),
    path('models/<int:pk>/json/', api_views.CobraModelDetailJsonView.as_view(), name='cobramodel_detail_json'),
    path('models/create/', views.CobraModelCreateView.as_view(), name='cobramodel_create_form'),
    path('models/<int:pk>/delete/', views.CobraModelDeleteView.as_view(), name='cobramodel_confirm_delete'),
    path('models/<int:pk>/update/', views.CobraModelUpdateView.as_view(), name='cobramodel_update_form'),
    path('models/<int:pk>/reaction_update_bound/', views.CobraModelReactionUpdateBoundView.as_view(),
         name='cobramodel_reaction_update_bound_form'),
    path('models/<int:pk>/change/<int:change_pk>/restore/', views.CobraModelChangeRestoreView.as_view(),
         name='cobramodel_change_restore'),

    path('models/<int:model_pk>/fba/', views.CobraFbaListView.as_view(), name='cobrafba_list'),
    path('models/<int:model_pk>/fba/<int:pk>/', views.CobraFbaDetailView.as_view(), name='cobrafba_detail'),
    path('models/<int:model_pk>/fba/<int:pk>/json/', api_views.CobraFbaDetailJsonView.as_view(),
         name='cobrafba_detail_json'),
    path('models/<int:model_pk>/fba/create/', views.CobraFbaCreateView.as_view(), name='cobrafba_create_form'),
    path('models/<int:model_pk>/fba/<int:pk>/delete/', views.CobraFbaDeleteView.as_view(),
         name='cobrafba_confirm_delete'),

    path('models/<int:model_pk>/rgefba/', views.CobraRgeFbaListView.as_view(), name='cobrargefba_list'),
    path('models/<int:model_pk>/rgefba/<int:pk>/', views.CobraRgeFbaDetailView.as_view(), name='cobrargefba_detail'),
    path('models/<int:model_pk>/rgefba/<int:pk>/json/', api_views.CobraRgeFbaDetailJsonView.as_view(),
         name='cobrargefba_detail_json'),
    path('models/<int:model_pk>/rgefba/create/', views.CobraRgeFbaCreateView.as_view(), name='cobrargefba_create_form'),
    path('models/<int:model_pk>/rgefba/<int:pk>/delete/', views.CobraRgeFbaDeleteView.as_view(),
         name='cobrargefba_confirm_delete'),

    path('models/<int:model_pk>/fva/', views.CobraFvaListView.as_view(), name='cobrafva_list'),
    path('models/<int:model_pk>/fva/<int:pk>/', views.CobraFvaDetailView.as_view(), name='cobrafva_detail'),
    path('models/<int:model_pk>/fva/<int:pk>/json', api_views.CobraFvaDetailJsonView.as_view(),
         name='cobrafva_detail_json'),
    path('models/<int:model_pk>/fva/create/', views.CobraFvaCreateView.as_view(), name='cobrafva_create_form'),
    path('models/<int:model_pk>/fva/<int:pk>/delete/', views.CobraFvaDeleteView.as_view(),
         name='cobrafva_confirm_delete'),
]

backend/share/urls.py
from django.urls import path

from . import views

app_name = 'share'
urlpatterns = [
    path('create/', views.CreateShareLinkView.as_view(), name='create_share'),
    path('model/<int:pk>', views.ModelShareView.as_view(), name='shared_cobra_model'),
    path('addToModel/', views.AddToMyModel.as_view(), name='add_to_model')
    # path('reaction/<int:pk>', views.ReactionShareView.as_view(), name='shared_cobra_reaction'),
    # path('metabolite/<int:pk>', views.MetaboliteShareView.as_view(), name='shared_cobra_metabolite'),
]

backend/cobra_wrapper/views.py
import json

from django.shortcuts import get_object_or_404, reverse, Http404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, FormView, View
from django.views.generic.edit import DeletionMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import Form
from django.utils import timezone

from . import models, forms
from .utils import load_comma_separated_str

from backend.celery import app


class CobraModelListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return models.CobraModel.objects.filter(owner=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)
        context_data['form'] = forms.CobraModelCreateForm()
        return context_data


class CobraModelDetailView(LoginRequiredMixin, DetailView):
    def get_object(self, queryset=None):
        return get_object_or_404(models.CobraModel, owner=self.request.user, pk=self.kwargs['pk'])

    def get_update_forms(self):
        return [form() for form in forms.cobra_model_update_forms.values()]

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['forms'] = self.get_update_forms()
        context_data['reactions'] = json.loads(self.object.reactions)

        def form_mount_reaction_id(cobra_id: str) -> forms.CobraModelReactionUpdateBoundForm:
            form = forms.CobraModelReactionUpdateBoundForm()
            form.fields['cobra_id'].initial = cobra_id
            return form

        # Do not render this in template
        # context_data['reaction_forms'] = [form_mount_reaction_id(reaction['cobra_id']) for reaction in
        #                                   context_data['reactions']]
        context_data['metabolites'] = json.loads(self.object.metabolites)
        context_data['genes'] = json.loads(self.object.genes)
        context_data['latest_changes'] = models.CobraModelChange.objects.filter(model=self.object)[:10]
        context_data['change_line_len'] = context_data['latest_changes'].count() * 95

        # keywords = set()
        # reaction_dict_list = [
        #     json.loads(change.reaction_info)
        #     for change in models.CobraModelChange.objects.filter(
        #         model=self.object, change_type='add_reaction')[:10]
        # ]
        # for reaction_dict in reaction_dict_list:
        #     for reaction in reaction_dict['reactions']:
        #         keywords.add(reaction['name'])
        #         keywords.update(reaction['metabolites'])
        #         keywords.update(reaction['genes'])

        # context_data['biobricks'] = search_biobricks(*keywords)

        biobricks = models.CobraBiobrick.objects.filter(cobra_model=self.object)
        context_data['biobricks'] = biobricks
        return context_data


class CobraModelMapView(LoginRequiredMixin, TemplateView):
    template_name = 'cobra_wrapper/cobramodel_map.html'


class CobraModelCreateView(LoginRequiredMixin, FormView):
    http_method_names = ['post']
    template_name = 'cobra_wrapper/cobramodel_list.html'
    form_class = forms.CobraModelCreateForm

    def form_valid(self, form: forms.CobraModelCreateForm):
        self.new_model = form.save(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return self.new_model.get_absolute_url()


class CobraModelDeleteView(LoginRequiredMixin, DeletionMixin, View):
    http_method_names = ['post']
    success_url = reverse_lazy('cobra_wrapper:cobramodel_list')

    def get_object(self):
        return get_object_or_404(models.CobraModel, owner=self.request.user, pk=self.kwargs['pk'])


class CobraModelUpdateView(LoginRequiredMixin, FormView):
    http_method_names = ['post']
    template_name_suffix = '_update_form'

    def get_object(self):
        return get_object_or_404(models.CobraModel, owner=self.request.user, pk=self.kwargs['pk'])

    def get_forms(self):
        return [form() for form in forms.cobra_model_update_forms.values()]

    def get_form_class(self):
        change_type = self.request.POST.get('change_type', None)
        try:
            return forms.cobra_model_update_forms[change_type]
        except KeyError:
            if self.request.method == 'GET':
                return None
            else:
                raise Http404()

    def get_form(self, form_class=None):
        self.form_class = self.get_form_class()
        if self.form_class is None:
            return None
        else:
            form = super().get_form()
            self.object = self.get_object()
            form.model_object = self.object
            return form

    def form_valid(self, form):
        form.save(self.object)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('cobra_wrapper:cobramodel_detail', kwargs={'pk': self.object.pk})


# class CobraModelChangeRestoreView(FormView):
#     http_method_names = ['post']
#     form_class = forms.CobraModelChangeRestoreForm
#
#     def get_object(self):
#         model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['pk'], owner=self.request.user)
#         return get_object_or_404(models.CobraModelChange, pk=self.kwargs['change_pk'], model=model_object)
#
#     def form_valid(self, form: forms.CobraModelChangeRestoreForm):
#         change = self.get_object()
#         self.new_model = change.restore(name=form.cleaned_data['name'], desc=form.cleaned_data['desc'])
#
#     def get_success_url(self):
#         return reverse(self.new_model)


class CobraModelChangeRestoreView(View):
    http_method_names = ['post']

    def get_object(self):
        model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['pk'], owner=self.request.user)
        return get_object_or_404(models.CobraModelChange, pk=self.kwargs['change_pk'], model=model_object)

    def post(self, request, *args, **kwargs):
        change = self.get_object()
        new_model = change.restore('Restored from {}'.format(change.model.name),
                                   timezone.now().strftime('%Y-%m-%d %H:%M:%S'))
        return redirect(new_model)


class CobraModelReactionUpdateBoundView(FormView):
    http_method_names = ['post']
    template_name = 'cobra_wrapper/cobramodel_list.html'
    form_class = forms.CobraModelReactionUpdateBoundForm

    def get_form(self, form_class=None):
        form = super().get_form()
        form.model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['pk'])
        return form

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('cobra_wrapper:cobramodel_detail', kwargs={'pk': self.kwargs['pk']})


class TemplateAddModelPkMixin:
    def get_context_data(self: TemplateView, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_pk'] = self.kwargs['model_pk']
        return context


class InsertModelForFormMixin:
    def get_form(self: FormView, form_class=None):
        self.model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        form = super().get_form()
        form.model_object = self.model_object
        return form


class CobraFbaListView(LoginRequiredMixin, TemplateAddModelPkMixin, ListView):
    def get_queryset(self):
        model = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return model.fba_list.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['form'] = forms.CobraFbaForm()
        return context_data


class CobraFbaDetailView(LoginRequiredMixin, TemplateAddModelPkMixin, DetailView):
    def get_object(self, queryset=None):
        self.model_object = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return get_object_or_404(self.model_object.fba_list.all(), pk=self.kwargs['pk'])


class CobraFbaCreateView(LoginRequiredMixin, InsertModelForFormMixin, TemplateAddModelPkMixin, CreateView):
    http_method_names = ['post']
    template_name = 'cobra_wrapper/cobrafba_list.html'
    model = models.CobraFba
    form_class = forms.CobraFbaForm

    def form_valid(self, form: Form):
        form.instance.model = self.model_object
        response = super().form_valid(form)
        result = app.send_task(
            'cobra_computation.tasks.cobra_fba',
            kwargs={
                'pk': self.object.pk,
                'model_sbml': self.model_object.sbml_content,
                'deleted_genes': load_comma_separated_str(form.cleaned_data['deleted_genes']),
                'computation_type': 'normal',
            },
            queue='cobra_feeds',
            routing_key='cobra_feed.fba',
        )
        self.object.task_id = result.id
        self.object.save()
        return response

    def get_success_url(self):
        return reverse('cobra_wrapper:cobrafba_list', kwargs={'model_pk': self.kwargs['model_pk']})


class CobraFbaDeleteView(LoginRequiredMixin, DeletionMixin, View):
    http_method_names = ['post']

    def get_object(self):
        model = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return get_object_or_404(model.fba_list.all(), pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse('cobra_wrapper:cobrafba_list', kwargs={'model_pk': self.kwargs['model_pk']})


class CobraRgeFbaListView(LoginRequiredMixin, TemplateAddModelPkMixin, ListView):
    def get_queryset(self):
        model = get_object_or_404(models.CobraModel, pk=self.kwargs['model_pk'], owner=self.request.user)
        return model.rgefba_list.all()

    def get_context_data(self, **kwargs):

backend/cobra_wrapper/templates/cobra_wrapper/cobrafba_list.html
{% extends 'base.html' %}

{% load cobra_wrapper_tags %}
{% load crispy_forms_tags %}

{% block title %}All FBA{% endblock title %}

{% block content %}
    <div class="banner w-100">
        <div class="container d-flex align-items-center">
            <div class="icon bg-info text-white d-flex justify-content-center align-items-center">
                <i class="fa fa-area-chart fa-2x"></i>
            </div>
            <div class="des ml-3">
                <h5>My Models</h5>
                <div>Here contains your computational models.</div>
            </div>
        </div>
    </div>
    <div id="my-models" class="container" style="padding: 0px"><br>
        {% for object in object_list %}
        {% if forloop.counter0|divisibleby:3 %}
            <div class="row show_card pt-3">
        {% endif %}
                <div class="col-4">
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #d4edda; color: #155724">
                                <td>desc</td>
                                <td>{{ object.desc }}</td>
                        </div>
                        <div class="card-body">
                            <table>
                                <tbody>
                                {% comment %}
                                <tr>
                                    <td>start_time</td>
                                    <td>{{ object.start_time }}</td>
                                </tr>
                                {% endcomment %}
                                <tr>
                                    <td>status</td>
                                    <td>{{ object|check_result_status }}</td>
                                </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'cobra_wrapper:cobrafba_detail' model_pk object.pk %}"
                               class="btn btn-outline-light btn-side-circle text-hover-green">Detail</a>
                        </div>
                        <div class="card-footer text-muted">
                            {{ object.start_time }}
                        </div>
                    </div>
                </div>
                {% if forloop.counter0|add:1|divisibleby:3 %}
            </div>
        {% endif %}
        {% endfor %}
        <div class="btn-group-fixed">
            <div class="row changeable">
                <button class="btn btn-outline-light btn-circle text-hover-green" data-toggle="modal"
                        data-target="#ModalPlus">
                    <i class="fa fa-plus" aria-hidden="true" style="line-height: 38px;"></i>
                </button>
            </div>
            <div class="row">
                <button type="button" class="btn btn-outline-light btn-circle text-hover-green"
                        href="{% url 'cobra_wrapper:cobramodel_detail' model_pk %}">
                    <i class="fa fa-reply" aria-hidden="true"></i>
                </button>
            </div>
            {% comment %}
            <div class="row">
                <button type="button" class="btn btn-outline-light btn-circle text-hover-green slide">
                    <i class="fa fa fa-chevron-down" aria-hidden="true"></i>
                </button>
            </div>
            {% endcomment %}
        </div>
    </div>

    <div class="modal fade" id="ModalPlus" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Create a new FBA</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'cobra_wrapper:cobrafba_create_form' model_pk %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
						{{ form|crispy }}
                    </div>
                    <div class="modal-footer">
                        <input type="reset" class="btn btn-secondary" value="Reset">
                        <input type="submit" class="btn btn-outline-light text-hover-green" value="Create">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $('button.slide').click(function () {
            if ($('.btn-group-fixed div.changeable').css('display') === 'none') {
                $('.btn-group-fixed div.changeable').fadeIn();
                $('button.slide').css({
                    'transform': 'rotate(0deg)'
                })
            } else {
                $('.btn-group-fixed div.changeable').fadeOut();
                $('button.slide').css({
                    'transform': 'rotate(180deg)'
                })
            }
        });

        $('button.change').click(function () {
            if ($('div.show_card').css('display') === 'flex') {
                $('div.show_card').css('display', 'none');
                $('div.show_plain').css('display', 'block');
                $('.change_icon').addClass('fa-th').removeClass('fa-th-list');
            } else {
                $('div.show_card').css('display', 'flex');
                $('div.show_plain').css('display', 'none');
                $('.change_icon').removeClass('fa-th').addClass('fa-th-list');
            }
        });
        {% if form.errors %}
            $(document).ready(function () {
                $("#ModalPlus").modal('toggle');
            });
            $(".invalid-feedback").show();
        {% endif %}
    </script>
{% endblock content %}

backend/cobra_wrapper/templates/cobra_wrapper/cobrafva_detail.html
{% extends 'base.html' %}

{% load static %}
{% load cobra_wrapper_tags %}

{% block title %}FVA Result of {{ object }}{% endblock title %}

{% block content %}

    <script src="{% static "javascript/jquery.min.js" %}"></script>
    <script src="{% static "javascript/popper.min.js" %}"></script>
    <script src="{% static "javascript/bootstrap.min.js" %}"></script>

    <style>
        #status {
            margin-left: 1em;
        }
    </style>

    <div class="container">
        <div class="row my-3">
            <div class="col-3">
                <h3>Description</h3>
                <p>{{ object.desc }}</p>
            </div>
            <div class="col-3">
                <h3>Start Time</h3>
                <p>{{ object.start_time }}</p>
            </div>
            <div class="col-3">
                <h3>Model</h3>
                <p>Click <a href="{% url 'cobra_wrapper:cobramodel_detail' model_pk %}">HERE</a></p>
            </div>
        </div>

        <div class="row my-2">
            <div class="alert alert-info" role="alert" id="status">
                Calculating Status: {{ object|check_result_status }}
            </div>
        </div>

        <div class="table-wrapper">
            <table class="table  table-hover table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Min Value</th>
                    <th>Max Value</th>
                </tr>
                </thead>
                <tbody id="res_body">

                </tbody>
            </table>
        </div>

        <div class="btn-group mt-2">
            <button class="btn btn-primary" id="more">More</button>
            <a href="{% url 'cobra_wrapper:cobrafva_confirm_delete' model_pk object.pk %}" class="btn btn-primary">Delete</a>
            <a href="{% url 'cobra_wrapper:cobrafva_list' model_pk %}" class="btn btn-primary">Return</a>
        </div>

    </div>

    <script>
        $(document).ready(function () {

            let res_data = [];
            let url = window.location.href;
            url += 'json';
            $.ajax({
                // url: 'http://127.0.0.1:8080/api/data',
                // api url
                url: url,
                // method: 'get',
                success: function (res) {
                    // console.log(res);
                    // res_data = JSON.parse(res);
                    res_data = res.results[0].components;
                    // console.log(res_data);
                    loadRes(Math.min(res_data.length, 20));


                },
                error: function (err) {
                    console.log('error when ajax.');
                    return;
                }
            });

            function loadRes(num = res_data.length) {
                let res_body = $('#res_body');
                let str = '';

                for (let i = 0; i < num; i++) {
                    str += '<tr><td>' + res_data[i].name + '</td>' +
                            '<td class="' + '' + '">' + res_data[i].min.toFixed(8) + '</td>' +
                            '<td class="' + '' + '">' + res_data[i].max.toFixed(8) + '</td>' +
                            '</tr>';
                }

                res_body.html(str);
            }

            $('#more').on('click', function () {
                loadRes(res_data.length);
            });

        });
    </script>




{% endblock content %}

backend/cobra_wrapper/templates/cobra_wrapper/cobrafva_list.html
{% extends 'base.html' %}

{% load cobra_wrapper_tags %}
{% load crispy_forms_tags %}

{% block title %}All FVA{% endblock title %}

{% block content %}
    <div class="banner w-100">
        <div class="container d-flex align-items-center">
            <div class="icon bg-info text-white d-flex justify-content-center align-items-center">
                <i class="fa fa-area-chart fa-2x"></i>
            </div>
            <div class="des ml-3">
                <h5>My Models</h5>
                <div>Here contains your computational models.</div>
            </div>
        </div>
    </div>
    <div id="my-models" class="container" style="padding: 0px"><br>
        {% for object in object_list %}
        {% if forloop.counter0|divisibleby:3 %}
            <div class="row show_card pt-3">
        {% endif %}
                <div class="col-4">
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #d4edda; color: #155724">
                                <td>desc</td>
                                <td>{{ object.desc }}</td>
                        </div>
                        <div class="card-body">
                            <table>
                                <tbody>
                                <tr>
                                    <td>start_time</td>
                                    <td>{{ object.start_time }}</td>
                                </tr>
                                <tr>
                                    <td>status</td>
                                    <td>{{ object|check_result_status }}</td>
                                </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'cobra_wrapper:cobrafva_detail' model_pk object.pk %}"
                               class="btn btn-outline-light btn-side-circle text-hover-green">Detail</a>
                        </div>
                        <div class="card-footer text-muted">
                            2019.9.1
                        </div>
                    </div>
                </div>
                {% if forloop.counter0|add:1|divisibleby:3 %}
            </div>
        {% endif %}
        {% endfor %}
        <div class="btn-group-fixed">
            <div class="row changeable">
                <button class="btn btn-outline-light btn-circle text-hover-green" data-toggle="modal"
                        data-target="#ModalPlus">
                    <i class="fa fa-plus" aria-hidden="true" style="line-height: 38px;"></i>
                </button>
            </div>
            <div class="row">
                <button type="button" class="btn btn-outline-light btn-circle text-hover-green"
                        href="{% url 'cobra_wrapper:cobramodel_detail' model_pk %}">
                    <i class="fa fa-reply" aria-hidden="true"></i>
                </button>
            </div>
            {% comment %}
            <div class="row">
                <button type="button" class="btn btn-outline-light btn-circle text-hover-green slide">
                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                </button>
            </div>
            {% endcomment %}
        </div>
    </div>

    <div class="modal fade" id="ModalPlus" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Create a new FVA</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'cobra_wrapper:cobrafva_create_form' model_pk %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </div>
                    <div class="modal-footer">
                        <input type="reset" class="btn btn-secondary" value="Reset">
                        <input type="submit" class="btn btn-outline-light text-hover-green" value="Create">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $('button.slide').click(function () {
            if ($('.btn-group-fixed div.changeable').css('display') === 'none') {
                $('.btn-group-fixed div.changeable').fadeIn();
                $('button.slide').css({
                    'transform': 'rotate(0deg)'
                })
            } else {
                $('.btn-group-fixed div.changeable').fadeOut();
                $('button.slide').css({
                    'transform': 'rotate(180deg)'
                })
            }
        });

        $('button.change').click(function () {
            if ($('div.show_card').css('display') === 'flex') {
                $('div.show_card').css('display', 'none');
                $('div.show_plain').css('display', 'block');
                $('.change_icon').addClass('fa-th').removeClass('fa-th-list');

            } else {
                $('div.show_card').css('display', 'flex');
                $('div.show_plain').css('display', 'none');
                $('.change_icon').removeClass('fa-th').addClass('fa-th-list');
            }
        });
        {% if form.errors %}
            $(document).ready(function () {
                $("#ModalPlus").modal('toggle');
            });
            $(".invalid-feedback").show();
        {% endif %}
    </script>
{% endblock content %}